/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as ClaimIdRouteImport } from './routes/claim.$id'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as PostIndexRouteImport } from './routes/post.index'
import { Route as PostFoundRouteImport } from './routes/post.found'
import { Route as PostLostRouteImport } from './routes/post.lost'
import { Route as RecoveryIdRouteImport } from './routes/recovery.$id'
import { Route as ReturnedIdRouteImport } from './routes/returned.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimIdRoute = ClaimIdRouteImport.update({
  id: '/claim/$id',
  path: '/claim/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PostIndexRoute = PostIndexRouteImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostFoundRoute = PostFoundRouteImport.update({
  id: '/post/found',
  path: '/post/found',
  getParentRoute: () => rootRouteImport,
} as any)
const PostLostRoute = PostLostRouteImport.update({
  id: '/post/lost',
  path: '/post/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryIdRoute = RecoveryIdRouteImport.update({
  id: '/recovery/$id',
  path: '/recovery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnedIdRoute = ReturnedIdRouteImport.update({
  id: '/returned/$id',
  path: '/returned/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/explore': typeof ExploreRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/claim/$id': typeof ClaimIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/post/found': typeof PostFoundRoute
  '/post/lost': typeof PostLostRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/returned/$id': typeof ReturnedIdRoute
  '/post/': typeof PostIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/explore': typeof ExploreRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/claim/$id': typeof ClaimIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/post/found': typeof PostFoundRoute
  '/post/lost': typeof PostLostRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/returned/$id': typeof ReturnedIdRoute
  '/post': typeof PostIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/claims': typeof ClaimsRoute
  '/explore': typeof ExploreRoute
  '/matches': typeof MatchesRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/safety': typeof SafetyRoute
  '/claim/$id': typeof ClaimIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/post/found': typeof PostFoundRoute
  '/post/lost': typeof PostLostRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/returned/$id': typeof ReturnedIdRoute
  '/post/': typeof PostIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/claims'
    | '/explore'
    | '/matches'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/claim/$id'
    | '/listing/$id'
    | '/post/found'
    | '/post/lost'
    | '/recovery/$id'
    | '/returned/$id'
    | '/post/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/claims'
    | '/explore'
    | '/matches'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/claim/$id'
    | '/listing/$id'
    | '/post/found'
    | '/post/lost'
    | '/recovery/$id'
    | '/returned/$id'
    | '/post'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/auth'
    | '/claims'
    | '/explore'
    | '/matches'
    | '/messages'
    | '/notifications'
    | '/profile'
    | '/safety'
    | '/claim/$id'
    | '/listing/$id'
    | '/post/found'
    | '/post/lost'
    | '/recovery/$id'
    | '/returned/$id'
    | '/post/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  ClaimsRoute: typeof ClaimsRoute
  ExploreRoute: typeof ExploreRoute
  MatchesRoute: typeof MatchesRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SafetyRoute: typeof SafetyRoute
  ClaimIdRoute: typeof ClaimIdRoute
  ListingIdRoute: typeof ListingIdRoute
  PostFoundRoute: typeof PostFoundRoute
  PostLostRoute: typeof PostLostRoute
  RecoveryIdRoute: typeof RecoveryIdRoute
  ReturnedIdRoute: typeof ReturnedIdRoute
  PostIndexRoute: typeof PostIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$id': {
      id: '/claim/$id'
      path: '/claim/$id'
      fullPath: '/claim/$id'
      preLoaderRoute: typeof ClaimIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/': {
      id: '/post/'
      path: '/post'
      fullPath: '/post/'
      preLoaderRoute: typeof PostIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/found': {
      id: '/post/found'
      path: '/post/found'
      fullPath: '/post/found'
      preLoaderRoute: typeof PostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post/lost': {
      id: '/post/lost'
      path: '/post/lost'
      fullPath: '/post/lost'
      preLoaderRoute: typeof PostLostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery/$id': {
      id: '/recovery/$id'
      path: '/recovery/$id'
      fullPath: '/recovery/$id'
      preLoaderRoute: typeof RecoveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returned/$id': {
      id: '/returned/$id'
      path: '/returned/$id'
      fullPath: '/returned/$id'
      preLoaderRoute: typeof ReturnedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  ClaimsRoute: ClaimsRoute,
  ExploreRoute: ExploreRoute,
  MatchesRoute: MatchesRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SafetyRoute: SafetyRoute,
  ClaimIdRoute: ClaimIdRoute,
  ListingIdRoute: ListingIdRoute,
  PostFoundRoute: PostFoundRoute,
  PostLostRoute: PostLostRoute,
  RecoveryIdRoute: RecoveryIdRoute,
  ReturnedIdRoute: ReturnedIdRoute,
  PostIndexRoute: PostIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
